plugins {
    id 'net.neoforged.moddev' version "$mdg_version"
}

version = project.ce_version+makeVersionSuffix()
group = "malte0811.controlengineering"
archivesBaseName = "ControlEngineering"

def version_replacements = [
        'mc_version': minecraft_version,
        'ie_version': ie_version,
        'ce_version': project.version,
        'neoforge_version': neoforge_version,
]

String makeVersionSuffix() {
    return System.getenv("GITHUB_ACTIONS") != null ? "-GH-" + System.getenv("GITHUB_RUN_NUMBER") : ""
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    inputs.properties version_replacements
    expand version_replacements
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

// Generate mods.toml on IDE import
neoForge.ideSyncTask generateModMetadata

sourceSets {
    main {
        resources {
            srcDir "$rootDir/src/generated/resources"
            srcDir generateModMetadata
        }
    }
    datagen {
        compileClasspath += main.output + main.compileClasspath
        runtimeClasspath += main.output + main.runtimeClasspath
    }
}

neoForge {
    version = "$neoforge_version"

    runs {
        client {
            client()
        }
        data {
            data()
            sourceSet = sourceSets.datagen
            programArguments = [
                    '--mod', 'controlengineering',
                    '--all',
                    '--output', file('src/generated/resources/').toString(),
                    '--validate',
                    '--existing', sourceSets.main.resources.srcDirs[0].toString()
            ]
        }
        server {
            server()
            programArguments = ["-nogui"]
        }
    }

    mods {
        controlengineering {
            sourceSet sourceSets.main
            // TODO can we not load this except in datagen
            sourceSet sourceSets.datagen
        }
    }
    unitTest {
        enable()
        testedMod = mods.controlengineering
    }
}

repositories {
    maven { // JEI & Tinkers
        name = 'DVS1 Maven FS'
        url = 'https://dvs1.progwml6.com/files/maven'
    }
    maven {
        name = "BlameJared"
        url = "https://maven.blamejared.com/"
    }
}

dependencies {
    runtimeOnly "blusunrize.immersiveengineering:ImmersiveEngineering:${ie_version}"
    compileOnly "blusunrize.immersiveengineering:ImmersiveEngineering:${ie_version}:api"
    compileOnly "malte0811:DualCodecs:0.1.2"
    datagenImplementation "blusunrize.immersiveengineering:ImmersiveEngineering:${ie_version}:datagen"
    testImplementation('junit:junit:4.13')
}

def customGradle = rootProject.file('custom.gradle');
if (customGradle.exists()) {
    apply from: customGradle;
}

task sourcesJar(type: Jar, dependsOn: classes) {
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

artifacts {
    archives sourcesJar
}

//Minimize/optimize all png files, requires optipng on the PATH
// Credits: BrainStone
void minimizePNGFile(File file) {
    long size = file.length()
    exec {
        executable "optipng"
        args "-q", "-o7", "-zm1-9", "-strip", "all", file
    }
    long newSize = file.length()
    if (newSize < size) {
        System.out.format("Reduced File size of %s from %d bytes to %d bytes (reduced by %.2f%%)\n",
                file, size, newSize, ((double) (size - newSize)) / ((double) size) * 100.0)
    }
}

task optimizePng {
    def pngPatterns = ["**/*.png"]
    doLast {
        //Ensure the logo is minimized (we add this file to each jar)
        //Minimize any PNGs in the source sets
        for (dir in sourceSets.main.resources.srcDirs) {
            fileTree(dir: dir, includes: pngPatterns).each { minimizePNGFile(it) }
        }
    }
}
