modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/malte0811/ControlEngineering/issues"
license = "MIT"

[[mods]]
modId = "controlengineering"
version = "${ce_version}"
displayName = "Control Engineering"
authors = "malte0811"
logoFile = "logo.png"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/control-engineering"
description = '''
An addon for Immersive Engineering providing control panels and logic cabinets among other related devices
'''
[[dependencies.controlengineering]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.controlengineering]]
modId = "immersiveengineering"
mandatory = true
versionRange = "[${ie_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.controlengineering]]
  modId="neoforge"
  type = "required"
  versionRange="[${neoforge_version},)"
  ordering="NONE"
  side="BOTH"

[[dependencies.controlengineering]]
  modId="minecraft"
  type = "required"
  versionRange="[${mc_version}]"
  ordering="NONE"
  side="BOTH"

[[mixins]]
  config="controlengineering.mixin.json"
